## 问：说说Python中的异常捕获？

## 答：每个程序，经常会报出一些异常，异常的原因一方面可能是写程序时由于疏忽或者考虑不全造成了错误，这时就需要根据异常找到出错点，进行分析改正；另一方面，有些异常是不可避免的，但我们可以对异常进行捕获处理，防止程序终止。

python的异常捕获常用`try...except...`结构，把可能发生错误的语句放在`try`模块里，用`except`来处理异常，每一个`try`，都必须至少对应一个`except`。此外，与python异常相关的关键字主要有

| 关键字 | 关键字说明 |
| :-: | :-: |
| try/except | 捕获异常并处理 |
| pass       | 忽略异常 |
| as         | 定义异常实例 （except MyError as e）|
| else       | 如果try中的语句没有异常，则执行else |
| finally    | 无论是否出现异常，都执行 |
| raise      | 抛出/引发异常 |


### 捕获所有异常
> https://www.jianshu.com/p/35a668fa1e54

包括键盘中断和程序退出请求（用`sys.exit()`就无法退出程序了，因为异常被捕获了），因此**慎用**。

```py
try:
     <语句>
except:
      print('异常说明')
```

### 捕获指定异常
```py
try:
     <语句>
except <异常名>:
      print('异常说明')
```

### 万能异常
```py
try:
     <语句>
except Exception:
      print('异常说明')
```

例

```py
try:
    f = open("file-not-exists", "r")
except IOError as e:
    print("open exception: %s: %s" %(e.errno, e.strerror))
```

### 捕获多个异常

- 一个except同时处理多个异常，不区分优先级

```py
try:
     <语句>
except (<异常名1>, <异常名2>, ...):
      print('异常说明')
```

- 区分优先级
```py
try:
     <语句>
except <异常名1>:
      print('异常说明1')
except <异常名2>:
      print('异常说明2')
except <异常名3>:
      print('异常说明3')
```
该种异常处理语法的规则是：

   - 执行try下的语句，如果引发异常，则执行过程会跳到第一个except语句。

   - 如果第一个except中定义的异常与引发的异常匹配，则执行该except中的语句。

   - 如果引发的异常不匹配第一个except，则会搜索第二个except，允许编写的except数量没有限制。

   - 如果所有的except都不匹配，则异常会传递到下一个调用本代码的最高层try代码中。


### 异常中的else
如果判断完没有某些异常之后还想做其他事，就可以使用下面这样的else语句。
```py
try:
     <语句>
except <异常名1>:
      print('异常说明1')
except <异常名2>:
      print('异常说明2')
else:
      <语句>  # try语句中没有异常则执行此段代码
```

### 异常中的finally
try...finally...语句无论是否发生异常都将会执行最后的代码。
```py
try:
     <语句>
finally:
     <语句>
```

示例
```py
str1 = 'hello world'
try:
    int(str1)
except IndexError as e:
    print(e)
except KeyError as e:
    print(e)
except ValueError as e:
    print(e)
else:
    print('try内没有异常')
finally:
    print('无论异常与否,都会执行我')
```

### raise主动触发异常
可以使用`raise`语句自己触发异常，`raise`语法格式如下：
```py
raise [Exception [, args [, traceback]]]
```
> 语句中`Exception`是异常的类型（例如`ValueError`），参数是一个异常参数值。该参数是可选的，如果不提供，异常的参数是"`None`"。最后一个参数是跟踪异常对象，也是可选的（在实践中很少使用）。

例
```py
def not_zero(num):
    try:
        if num == 0:
            raise ValueError('参数错误')
        return num
    except Exception as e:
        print(e)

not_zero(0)
```